config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' } 
  root 'home#dashboard'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/calculator.rb
class Calculator < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :notes, as: :notable
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :notes, as: :notable
end

app/models/hospital.rb
class Hospital < ApplicationRecord
    validates :name, presence: true
    validates :facility, presence: true
    validates :name, length: { minimum: 2 }
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :doctors, through: :appointments
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/product.rb
class Product < ApplicationRecord
    validates :productname, presence: true
    validates :quantity, presence: true
    validates :brand, presence: true
    validates :prize, presence: true
    validates :prize, numericality: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/registration.rb
class Registration < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
    has_many :players
    validate :custom_validation
    private def custom_validation
      if  (sport_name=="")
        self.errors[:base] <<"plzz fill sport name"
      end
    end
end

app/models/test.rb
class Test < ApplicationRecord
    mount_uploader :image, FileUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  mount_uploader :image, ImageUploader

   # Enum role for users      
   enum role: [:super_admin, :user]
   after_initialize :set_default_role, :if => :new_record?
   def set_default_role
     self.role ||= :user
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
  def index 
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Person', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to "About", home_about_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Registrations", registrations_path, class:"nav-link"%>
      </li>
       <li class="nav-item">
      <%= link_to "New Registration", new_registration_path, class:"nav-link"%>
      </li>
       <% if user_signed_in? %>
      <li class="nav-item">
       <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
      </li>
       <li class="nav-item">
      <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Sign In",  new_user_session_path, class:"nav-link"%>
      </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/dashboard.html.erb
<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Sale & Revenue Start -->
<div class="container-fluid pt-4 px-4">
  <div class="row g-4">
    <div class="col-sm-6 col-xl-3">
      <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-line fa-3x text-primary"></i>
          <div class="ms-3">
            <p class="mb-2">Today Sale</p>
            <h6 class="mb-0">$1234</h6>
          </div>
      </div>
    </div>
    <div class="col-sm-6 col-xl-3">
      <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
          <i class="fa fa-chart-bar fa-3x text-primary"></i>
          <div class="ms-3">
              <p class="mb-2">Total Sale</p>
              <h6 class="mb-0">$1234</h6>
          </div>
      </div>
    </div>
    <div class="col-sm-6 col-xl-3">
      <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-area fa-3x text-primary"></i>
          <div class="ms-3">
            <p class="mb-2">Today Revenue</p>
            <h6 class="mb-0">$1234</h6>
          </div>
      </div>
    </div>
    <div class="col-sm-6 col-xl-3">
      <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-pie fa-3x text-primary"></i>
          <div class="ms-3">
            <p class="mb-2">Total Revenue</p>
            <h6 class="mb-0">$1234</h6>
          </div>
      </div>
    </div> 
  </div>
</div>

<!-- Sales Chart Start -->
<div class="container-fluid pt-4 px-4">
  <div class="row g-4">
    <div class="col-sm-12 col-xl-6">
      <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Worldwide Sales</h6>
            <a href="">Show All</a>
        </div>
        <canvas id="worldwide-sales"></canvas>
      </div>
    </div>
    <div class="col-sm-12 col-xl-6">
      <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Salse & Revenue</h6>
            <a href="">Show All</a>
        </div>
        <canvas id="salse-revenue"></canvas>
      </div>
    </div>
  </div>
</div>

<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
  <div class="bg-light text-center rounded p-4">
    <div class="d-flex align-items-center justify-content-between mb-4">
      <h6 class="mb-0">Recent Salse</h6>
      <a href="">Show All</a>
  </div>
    <div class="table-responsive">
      <table class="table text-start align-middle table-bordered table-hover mb-0">
          <thead>
              <tr class="text-dark">
                  <th scope="col"><input class="form-check-input" type="checkbox"></th>
                  <th scope="col">Date</th>
                  <th scope="col">Invoice</th>
                  <th scope="col">Customer</th>
                  <th scope="col">Amount</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
              </tr>
          </thead>
        <tbody>
              <tr>
                  <td><input class="form-check-input" type="checkbox"></td>
                  <td>01 Jan 2045</td>
                  <td>INV-0123</td>
                  <td>Jhon Doe</td>
                  <td>$123</td>
                  <td>Paid</td>
                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
              </tr>
              <tr>
                  <td><input class="form-check-input" type="checkbox"></td>
                  <td>01 Jan 2045</td>
                  <td>INV-0123</td>
                  <td>Jhon Doe</td>
                  <td>$123</td>
                  <td>Paid</td>
                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
              </tr>
              <tr>
                  <td><input class="form-check-input" type="checkbox"></td>
                  <td>01 Jan 2045</td>
                  <td>INV-0123</td>
                  <td>Jhon Doe</td>
                  <td>$123</td>
                  <td>Paid</td>
                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
              </tr>
              <tr>
                  <td><input class="form-check-input" type="checkbox"></td>
                  <td>01 Jan 2045</td>
                  <td>INV-0123</td>
                  <td>Jhon Doe</td>
                  <td>$123</td>
                  <td>Paid</td>
                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
              </tr>
              <tr>
                  <td><input class="form-check-input" type="checkbox"></td>
                  <td>01 Jan 2045</td>
                  <td>INV-0123</td>
                  <td>Jhon Doe</td>
                  <td>$123</td>
                  <td>Paid</td>
                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
              </tr>
          </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Widgets Start -->
<div class="container-fluid pt-4 px-4">
  <div class="row g-4">
    <div class="col-sm-12 col-md-6 col-xl-4">
      <div class="h-100 bg-light rounded p-4">
          <div class="d-flex align-items-center justify-content-between mb-2">
              <h6 class="mb-0">Messages</h6>
              <a href="">Show All</a>
          </div>
          <div class="d-flex align-items-center border-bottom py-3">
              <img class="rounded-circle flex-shrink-0" src="<%= asset_url("theme_images/user.jpg") %>" alt="" style="width: 40px; height: 40px;">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 justify-content-between">
                      <h6 class="mb-0">Jhon Doe</h6>
                      <small>15 minutes ago</small>
                  </div>
                  <span>Short message goes here...</span>
              </div>
          </div>
          <div class="d-flex align-items-center border-bottom py-3">
              <img class="rounded-circle flex-shrink-0" src="<%= asset_url("theme_images/user.jpg") %>" alt="" style="width: 40px; height: 40px;">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 justify-content-between">
                      <h6 class="mb-0">Jhon Doe</h6>
                      <small>15 minutes ago</small>
                  </div>
                  <span>Short message goes here...</span>
              </div>
          </div>
          <div class="d-flex align-items-center border-bottom py-3">
              <img class="rounded-circle flex-shrink-0" src="<%= asset_url("theme_images/user.jpg") %>" alt="" style="width: 40px; height: 40px;">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 justify-content-between">
                      <h6 class="mb-0">Jhon Doe</h6>
                      <small>15 minutes ago</small>
                  </div>
                  <span>Short message goes here...</span>
              </div>
          </div>
          <div class="d-flex align-items-center pt-3">
              <img class="rounded-circle flex-shrink-0" src="<%= asset_url("theme_images/user.jpg") %>" alt="" style="width: 40px; height: 40px;">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 justify-content-between">
                      <h6 class="mb-0">Jhon Doe</h6>
                      <small>15 minutes ago</small>
                  </div>
                  <span>Short message goes here...</span>
              </div>
          </div>
      </div>
  </div>
  <div class="col-sm-12 col-md-6 col-xl-4">
      <div class="h-100 bg-light rounded p-4">
          <div class="d-flex align-items-center justify-content-between mb-4">
              <h6 class="mb-0">Calender</h6>
              <a href="">Show All</a>
          </div>
          <div id="calender"></div>
      </div>
  </div>
  <div class="col-sm-12 col-md-6 col-xl-4">
      <div class="h-100 bg-light rounded p-4">
          <div class="d-flex align-items-center justify-content-between mb-4">
              <h6 class="mb-0">To Do List</h6>
              <a href="">Show All</a>
          </div>
          <div class="d-flex mb-2">
              <input class="form-control bg-transparent" type="text" placeholder="Enter task">
              <button type="button" class="btn btn-primary ms-2">Add</button>
          </div>
          <div class="d-flex align-items-center border-bottom py-2">
              <input class="form-check-input m-0" type="checkbox">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 align-items-center justify-content-between">
                      <span>Short task goes here...</span>
                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                  </div>
              </div>
          </div>
          <div class="d-flex align-items-center border-bottom py-2">
              <input class="form-check-input m-0" type="checkbox">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 align-items-center justify-content-between">
                      <span>Short task goes here...</span>
                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                  </div>
              </div>
          </div>
          <div class="d-flex align-items-center border-bottom py-2">
              <input class="form-check-input m-0" type="checkbox" checked>
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 align-items-center justify-content-between">
                      <span><del>Short task goes here...</del></span>
                      <button class="btn btn-sm text-primary"><i class="fa fa-times"></i></button>
                  </div>
              </div>
          </div>
          <div class="d-flex align-items-center border-bottom py-2">
              <input class="form-check-input m-0" type="checkbox">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 align-items-center justify-content-between">
                      <span>Short task goes here...</span>
                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                  </div>
              </div>
          </div>
          <div class="d-flex align-items-center pt-2">
              <input class="form-check-input m-0" type="checkbox">
              <div class="w-100 ms-3">
                  <div class="d-flex w-100 align-items-center justify-content-between">
                      <span>Short task goes here...</span>
                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>
  <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>